package com.sweng22g1.serverapp;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * This is auto-generated by Spring Boot
 * 
 * @author Spring Boot
 * 
 */
@SpringBootTest(classes = ServerAppApplicationTests.class)
class ServerAppApplicationTests {

	@Test
	void contextLoads() {
	}
}